// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TbdDevelop.Mediator.Sagas.SqlServer.Context;

#nullable disable

namespace TbdDevelop.Mediator.Sagas.SqlServer.Migrations
{
    [DbContext(typeof(SagaDbContext))]
    partial class SagaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sagas")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TbdDevelop.Mediator.Sagas.Persistence.Models.Saga", b =>
                {
                    b.Property<Guid>("OrchestrationIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastTriggered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextTriggerTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("TriggerInterval")
                        .HasColumnType("time");

                    b.Property<string>("TypeIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("OrchestrationIdentifier")
                        .HasName("PK_saga_orchestration_id");

                    b.ToTable("Sagas", "sagas");
                });
#pragma warning restore 612, 618
        }
    }
}
